#!python3
# Chendl 2025-03-14
## Comment here

def subseq(s,t):
	start = 0
	ret = []
	i = 0
	while i < len(t):
		for j in range(start,len(s)):
			if t[i]==s[j]:
				ret.append(j+1)
				start = j + 1
				i += 1
				break
	return ret

if __name__ == "__main__":
	test_s = 'GCGTGCGCTCCGGTCTGACCGTCACCGTCCGCATTAATCTTTAAAGTGCGTAGAGAACAGCGCACGGGTATAAGTACGATGGTTGAATGTCCCGGATACTCAGTAACGCAGTTCGGAACC TATAAAAATATCGTCCTGCAGCCGGAGTTCAGTGACCGTGATACTCGTTCCGGCTAAAAGAAATAGGCGTTGGTGTGTCGGTCAGAGACCATGATCTACGGGCTAGCTCTTAACGGCCTTTCTAGCCCATAGGTACTGACTTCTGAAAGCGGAGAGCGGGCAGGTCACGACCGCACCCGAGCCCTGGCGGCTGAGGCACGGACAGAAAAATCAACAAATGCGTCTGGGTAAAAATCGGATGTCTATACTGGTACGAAAGAGTAGAGATAAATCGTACGTCAACGATCATGATACACCGGGGATTCCTATGTCCTTACATGGAGACAACAGGATCTCGTGGCGTATCATTACCGGTTATACCACTTGGAACCACAAGTGATCCCTAGGGCTATGTACTCGGGGTCAAAAGAATCCCTTATAACAGGACAGAAAAACTTCTAGATGAGGTTAGTTCTTAACTTAAAGCACTGATGATGCCAGGTCGTGGTCGCATAAGGGTGAGTCTTCAGGAAGGTAGGACATGTTCGGAGAAGGCGTATATCACGAATCTAGCCTCCTGCGTCCCAAAGTACAGCCGTCTAGGTTGCTCACGACCTATATATAGGAAACGCTCATCGGGTTTATCAGACAACACGTCGGGGCCAACATGAGTAATTACAGCGTGGTTAATCCAGCCTGCTTACGACTGAGAGGTAATTGGAG'
	test_t = 'GCGAGATCGTCGAGCGCGATGCTTACGCCGG'
	print(' '.join([str(i) for i in subseq(test_s,test_t)]))